// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'chatpdf-item-section-chatpdf-fullheight'
  | 'chatpdf-item-section-chatpdf-head-text'
  | 'chatpdf-item-section-chatpdf-sidenav-tooltip'
  | 'chatpdf-menuitem-addtochatpdf'
  | 'menuitem-addtochatpdf'
  | 'pref-cache-dir'
  | 'pref-help'
  | 'pref-llm-api-base'
  | 'pref-llm-api-key'
  | 'pref-llm-model'
  | 'pref-max-document-chars'
  | 'pref-mineru-token'
  | 'pref-system-prompt'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
