// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'chatpdf-menuitem-addtochatpdf'
  | 'chatpdf-menuitem-relatedsessions'
  | 'menuitem-addtochatpdf'
  | 'pref-agent-max-iterations'
  | 'pref-brave-search-api-key'
  | 'pref-cache-dir'
  | 'pref-enable-agent-mode'
  | 'pref-enable-web-tools'
  | 'pref-help'
  | 'pref-llm-api-base'
  | 'pref-llm-api-key'
  | 'pref-llm-model'
  | 'pref-max-document-chars'
  | 'pref-mineru-token'
  | 'pref-model-profiles'
  | 'pref-profile-name'
  | 'pref-system-prompt'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
