// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mineruToken": string;
      "llmApiBase": string;
      "llmApiKey": string;
      "llmModel": string;
      "cacheDir": string;
      "maxDocumentChars": number;
      "systemPrompt": string;
      "modelProfiles": string;
      "activeProfile": string;
    };
  }
}
