// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mineruToken": string;
      "mineruLanguage": string;
      "mineruTimeoutMinutes": number;
      "llmProvider": string;
      "llmApiBase": string;
      "llmApiKey": string;
      "llmModel": string;
      "llmThinkingMode": string;
      "llmThinkEffort": string;
      "cacheDir": string;
      "systemPrompt": string;
      "modelProfiles": string;
      "activeProfile": string;
      "panelWidth": number;
      "agentMaxIterations": number;
      "agentAutoContinue": boolean;
      "contextWindowTokens": number;
      "inputTokenLimit": number;
      "maxOutputTokens": number;
      "requestedOutputTokens": number;
      "imageTokenReserve": number;
      "tokenizerMode": string;
      "modelCapabilitiesRevision": number;
      "enableWebTools": boolean;
      "braveSearchApiKey": string;
      "debugLogMode": string;
      "debugLogRetentionDays": number;
    };
  }
}
