pref("mineruToken", "");
pref("llmApiBase", "https://api.deepseek.com/v1");
pref("llmApiKey", "");
pref("llmModel", "deepseek-chat");
pref("cacheDir", "");
pref("maxDocumentChars", 300000);
pref("systemPrompt", "");
pref("modelProfiles", "[]");
pref("activeProfile", "");
